// CHECKSTYLE:OFF
// Motivation: Generated class.
package org.kasource.kaevent.config;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



/**
 * Configuration of Ka Event. 
 * 		
 * Generated JAXB class.		
 * 
 * Don't use this class directly when programmatically creating a configuration, use the KaEventConfigBuilder 
 * instead.
 * 
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 * 
 * 
 * @version $Id$
 **/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "queueThread",
    "threadPoolExecutor",
    "beanResolver",
    "channelFactory",
    "events",
    "channels"
})
@XmlRootElement(name = "kaEventConfig")
public class KaEventConfig {

    protected KaEventConfig.QueueThread queueThread;
	protected KaEventConfig.ThreadPoolExecutor threadPoolExecutor;
    protected KaEventConfig.BeanResolver beanResolver;
    protected KaEventConfig.ChannelFactory channelFactory;
    protected KaEventConfig.Events events;
    @XmlElement(required = true)
    protected KaEventConfig.Channels channels;

    
    public KaEventConfig() { }
    
    public KaEventConfig(String scanClassPath) {
    	if (scanClassPath != null) {
    		events = new Events();
    		events.scanClassPath = scanClassPath.trim();
    	}
    }
    
    /**
     * Gets the value of the queueThread property.
     * 
     * @return
     *     possible object is
     *     {@link KaEventConfig.QueueThread }
     *     
     */
    public KaEventConfig.QueueThread getQueueThread() {
        return queueThread;
    }

    /**
     * Sets the value of the queueThread property.
     * 
     * @param value
     *     allowed object is
     *     {@link KaEventConfig.QueueThread }
     *     
     */
    public void setQueueThread(KaEventConfig.QueueThread value) {
        this.queueThread = value;
    }

    /**
     * Gets the value of the threadPoolExecutor property.
     * 
     * @return
     *     possible object is
     *     {@link KaEventConfig.ThreadPoolExecutor }
     *     
     */
    public KaEventConfig.ThreadPoolExecutor getThreadPoolExecutor() {
        return threadPoolExecutor;
    }

    /**
     * Sets the value of the threadPoolExecutor property.
     * 
     * @param value
     *     allowed object is
     *     {@link KaEventConfig.ThreadPoolExecutor }
     *     
     */
    public void setThreadPoolExecutor(KaEventConfig.ThreadPoolExecutor value) {
        this.threadPoolExecutor = value;
    }

    /**
     * Gets the value of the beanResolver property.
     * 
     * @return
     *     possible object is
     *     {@link KaEventConfig.BeanResolver }
     *     
     */
    public KaEventConfig.BeanResolver getBeanResolver() {
        return beanResolver;
    }

    /**
     * Sets the value of the beanResolver property.
     * 
     * @param value
     *     allowed object is
     *     {@link KaEventConfig.BeanResolver }
     *     
     */
    public void setBeanResolver(KaEventConfig.BeanResolver value) {
        this.beanResolver = value;
    }

    /**
     * Returns the channel factory.
     * 
     * @return Channel Factory.
     **/
    public KaEventConfig.ChannelFactory getChannelFactory() {
		return channelFactory;
	}

    /**
     * Set the channel factory.
     * 
     * @param channelFactory Set the Channel Factory to use.
     **/
	public void setChannelFactory(KaEventConfig.ChannelFactory channelFactory) {
		this.channelFactory = channelFactory;
	}
    
    /**
     * Gets the value of the events property.
     * 
     * @return
     *     possible object is
     *     {@link KaEventConfig.Events }
     *     
     */
    public KaEventConfig.Events getEvents() {
        return events;
    }

    /**
     * Sets the value of the events property.
     * 
     * @param value
     *     allowed object is
     *     {@link KaEventConfig.Events }
     *     
     */
    public void setEvents(KaEventConfig.Events value) {
        this.events = value;
    }

    /**
     * Gets the value of the channels property.
     * 
     * @return
     *     possible object is
     *     {@link KaEventConfig.Channels }
     *     
     */
    public KaEventConfig.Channels getChannels() {
        return channels;
    }

    /**
     * Sets the value of the channels property.
     * 
     * @param value
     *     allowed object is
     *     {@link KaEventConfig.Channels }
     *     
     */
    public void setChannels(KaEventConfig.Channels value) {
        this.channels = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class" type="{http://kasource.org}javaClass" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class BeanResolver {

        @XmlAttribute(name = "class")
        protected String clazz;

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

    }
    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ChannelFactory {

        @XmlAttribute(name = "class")
        protected String clazz;

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="channel" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="handle" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="event" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "channel"
    })
    public static class Channels {

        @XmlElement(required = true)
        protected List<KaEventConfig.Channels.Channel> channel;

        /**
         * Gets the value of the channel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the channel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChannel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link KaEventConfig.Channels.Channel }
         * 
         * 
         */
        public List<KaEventConfig.Channels.Channel> getChannel() {
            if (channel == null) {
                channel = new ArrayList<KaEventConfig.Channels.Channel>();
            }
            return this.channel;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="handle" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="event" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "handle"
        })
        public static class Channel {

            protected List<KaEventConfig.Channels.Channel.Handle> handle;
            @XmlAttribute(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String name;

            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlAttribute(required = false, name="class")
            protected String className;
            
            @XmlAttribute(required = false, name="filter")
            protected String filter;
            
            public String getFilter() {
				return filter;
			}

			public void setFilter(String filter) {
				this.filter = filter;
			}

			public String getClassName() {
				return className;
			}

			public void setClassName(String className) {
				this.className = className;
			}

			/**
             * Gets the value of the handle property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the handle property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHandle().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link KaEventConfig.Channels.Channel.Handle }
             * 
             * 
             */
            public List<KaEventConfig.Channels.Channel.Handle> getHandle() {
                if (handle == null) {
                    handle = new ArrayList<KaEventConfig.Channels.Channel.Handle>();
                }
                return this.handle;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="event" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Handle {

                @XmlAttribute(required = true)
                protected String event;

                /**
                 * Gets the value of the event property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public String getEvent() {
                    return event;
                }

                /**
                 * Sets the value of the event property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setEvent(String value) {
                    this.event = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="event" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice minOccurs="0">
     *                     &lt;element name="annotationMethodResolver" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                     &lt;element name="factoryMethodResolver">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;attribute name="factoryClass" use="required" type="{http://kasource.org}javaClass" />
     *                             &lt;attribute name="factoryMethod" use="required" type="{http://kasource.org}javaMethodName" />
     *                             &lt;attribute name="factoryMethodArgument" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="beanMethodResolver">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;attribute name="bean" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="switchMethodResolver">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="case" maxOccurs="unbounded">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                       &lt;attribute name="method" use="required" type="{http://kasource.org}javaMethodName" />
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                               &lt;element name="default">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;attribute name="method" use="required" type="{http://kasource.org}javaMethodName" />
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                             &lt;/sequence>
     *                             &lt;attribute name="keywordMethod" use="required" type="{http://kasource.org}javaMethodName" />
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="eventClass" use="required" type="{http://kasource.org}javaClass" />
     *                 &lt;attribute name="listenerInterface" use="required" type="{http://kasource.org}javaClass" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="scanClassPath" type="{http://kasource.org}javaPackage" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "event"
    })
    public static class Events {

        protected List<KaEventConfig.Events.Event> event;
        @XmlAttribute
        protected String scanClassPath;

        /**
         * Gets the value of the event property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the event property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link KaEventConfig.Events.Event }
         * 
         * 
         */
        public List<KaEventConfig.Events.Event> getEvent() {
            if (event == null) {
                event = new ArrayList<KaEventConfig.Events.Event>();
            }
            return this.event;
        }

        /**
         * Gets the value of the scanClassPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScanClassPath() {
            return scanClassPath;
        }

        /**
         * Sets the value of the scanClassPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScanClassPath(String value) {
            this.scanClassPath = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice minOccurs="0">
         *           &lt;element name="annotationMethodResolver" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *           &lt;element name="factoryMethodResolver">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;attribute name="factoryClass" use="required" type="{http://kasource.org}javaClass" />
         *                   &lt;attribute name="factoryMethod" use="required" type="{http://kasource.org}javaMethodName" />
         *                   &lt;attribute name="factoryMethodArgument" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *           &lt;element name="beanMethodResolver">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;attribute name="bean" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *           &lt;element name="switchMethodResolver">
         *             &lt;complexType>
         *               &lt;complexContent>
         *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                   &lt;sequence>
         *                     &lt;element name="case" maxOccurs="unbounded">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                             &lt;attribute name="method" use="required" type="{http://kasource.org}javaMethodName" />
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                     &lt;element name="default">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;attribute name="method" use="required" type="{http://kasource.org}javaMethodName" />
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                   &lt;/sequence>
         *                   &lt;attribute name="keywordMethod" use="required" type="{http://kasource.org}javaMethodName" />
         *                 &lt;/restriction>
         *               &lt;/complexContent>
         *             &lt;/complexType>
         *           &lt;/element>
         *         &lt;/choice>
         *       &lt;/sequence>
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="eventClass" use="required" type="{http://kasource.org}javaClass" />
         *       &lt;attribute name="listenerInterface" use="required" type="{http://kasource.org}javaClass" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "annotationMethodResolver",
            "factoryMethodResolver",
            "beanMethodResolver",
            "switchMethodResolver"
        })
        public static class Event {

            protected Object annotationMethodResolver;
            protected KaEventConfig.Events.Event.FactoryMethodResolver factoryMethodResolver;
            protected KaEventConfig.Events.Event.BeanMethodResolver beanMethodResolver;
            protected KaEventConfig.Events.Event.SwitchMethodResolver switchMethodResolver;
            @XmlAttribute(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String name;
            @XmlAttribute(required = true)
            protected String eventClass;
            @XmlAttribute(required = true)
            protected String listenerInterface;

            /**
             * Gets the value of the annotationMethodResolver property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getAnnotationMethodResolver() {
                return annotationMethodResolver;
            }

            /**
             * Sets the value of the annotationMethodResolver property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setAnnotationMethodResolver(Object value) {
                this.annotationMethodResolver = value;
            }

            /**
             * Gets the value of the factoryMethodResolver property.
             * 
             * @return
             *     possible object is
             *     {@link KaEventConfig.Events.Event.FactoryMethodResolver }
             *     
             */
            public KaEventConfig.Events.Event.FactoryMethodResolver getFactoryMethodResolver() {
                return factoryMethodResolver;
            }

            /**
             * Sets the value of the factoryMethodResolver property.
             * 
             * @param value
             *     allowed object is
             *     {@link KaEventConfig.Events.Event.FactoryMethodResolver }
             *     
             */
            public void setFactoryMethodResolver(KaEventConfig.Events.Event.FactoryMethodResolver value) {
                this.factoryMethodResolver = value;
            }

            /**
             * Gets the value of the beanMethodResolver property.
             * 
             * @return
             *     possible object is
             *     {@link KaEventConfig.Events.Event.BeanMethodResolver }
             *     
             */
            public KaEventConfig.Events.Event.BeanMethodResolver getBeanMethodResolver() {
                return beanMethodResolver;
            }

            /**
             * Sets the value of the beanMethodResolver property.
             * 
             * @param value
             *     allowed object is
             *     {@link KaEventConfig.Events.Event.BeanMethodResolver }
             *     
             */
            public void setBeanMethodResolver(KaEventConfig.Events.Event.BeanMethodResolver value) {
                this.beanMethodResolver = value;
            }

            /**
             * Gets the value of the switchMethodResolver property.
             * 
             * @return
             *     possible object is
             *     {@link KaEventConfig.Events.Event.SwitchMethodResolver }
             *     
             */
            public KaEventConfig.Events.Event.SwitchMethodResolver getSwitchMethodResolver() {
                return switchMethodResolver;
            }

            /**
             * Sets the value of the switchMethodResolver property.
             * 
             * @param value
             *     allowed object is
             *     {@link KaEventConfig.Events.Event.SwitchMethodResolver }
             *     
             */
            public void setSwitchMethodResolver(KaEventConfig.Events.Event.SwitchMethodResolver value) {
                this.switchMethodResolver = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the eventClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEventClass() {
                return eventClass;
            }

            /**
             * Sets the value of the eventClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEventClass(String value) {
                this.eventClass = value;
            }

            /**
             * Gets the value of the listenerInterface property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getListenerInterface() {
                return listenerInterface;
            }

            /**
             * Sets the value of the listenerInterface property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setListenerInterface(String value) {
                this.listenerInterface = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="bean" use="required" type="{http://www.w3.org/2001/XMLSchema}Name" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class BeanMethodResolver {

                @XmlAttribute(required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "Name")
                protected String bean;

                /**
                 * Gets the value of the bean property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBean() {
                    return bean;
                }

                /**
                 * Sets the value of the bean property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBean(String value) {
                    this.bean = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="factoryClass" use="required" type="{http://kasource.org}javaClass" />
             *       &lt;attribute name="factoryMethod" use="required" type="{http://kasource.org}javaMethodName" />
             *       &lt;attribute name="factoryMethodArgument" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class FactoryMethodResolver {

                @XmlAttribute(required = true)
                protected String factoryClass;
                @XmlAttribute(required = true)
                protected String factoryMethod;
                @XmlAttribute
                protected String factoryMethodArgument;

                /**
                 * Gets the value of the factoryClass property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFactoryClass() {
                    return factoryClass;
                }

                /**
                 * Sets the value of the factoryClass property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFactoryClass(String value) {
                    this.factoryClass = value;
                }

                /**
                 * Gets the value of the factoryMethod property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFactoryMethod() {
                    return factoryMethod;
                }

                /**
                 * Sets the value of the factoryMethod property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFactoryMethod(String value) {
                    this.factoryMethod = value;
                }

                /**
                 * Gets the value of the factoryMethodArgument property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFactoryMethodArgument() {
                    return factoryMethodArgument;
                }

                /**
                 * Sets the value of the factoryMethodArgument property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFactoryMethodArgument(String value) {
                    this.factoryMethodArgument = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="case" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="method" use="required" type="{http://kasource.org}javaMethodName" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="default">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;attribute name="method" use="required" type="{http://kasource.org}javaMethodName" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="keywordMethod" use="required" type="{http://kasource.org}javaMethodName" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "_case",
                "_default"
            })
            public static class SwitchMethodResolver {

                @XmlElement(name = "case", required = true)
                protected List<KaEventConfig.Events.Event.SwitchMethodResolver.Case> _case;
                @XmlElement(name = "default", required = true)
                protected KaEventConfig.Events.Event.SwitchMethodResolver.Default _default;
                @XmlAttribute(required = true)
                protected String keywordMethod;

                /**
                 * Gets the value of the case property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the case property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCase().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link KaEventConfig.Events.Event.SwitchMethodResolver.Case }
                 * 
                 * 
                 */
                public List<KaEventConfig.Events.Event.SwitchMethodResolver.Case> getCase() {
                    if (_case == null) {
                        _case = new ArrayList<KaEventConfig.Events.Event.SwitchMethodResolver.Case>();
                    }
                    return this._case;
                }

                /**
                 * Gets the value of the default property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link KaEventConfig.Events.Event.SwitchMethodResolver.Default }
                 *     
                 */
                public KaEventConfig.Events.Event.SwitchMethodResolver.Default getDefault() {
                    return _default;
                }

                /**
                 * Sets the value of the default property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link KaEventConfig.Events.Event.SwitchMethodResolver.Default }
                 *     
                 */
                public void setDefault(KaEventConfig.Events.Event.SwitchMethodResolver.Default value) {
                    this._default = value;
                }

                /**
                 * Gets the value of the keywordMethod property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getKeywordMethod() {
                    return keywordMethod;
                }

                /**
                 * Sets the value of the keywordMethod property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setKeywordMethod(String value) {
                    this.keywordMethod = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="method" use="required" type="{http://kasource.org}javaMethodName" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Case {

                    @XmlAttribute(required = true)
                    protected String value;
                    @XmlAttribute(required = true)
                    protected String method;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the method property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getMethod() {
                        return method;
                    }

                    /**
                     * Sets the value of the method property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setMethod(String value) {
                        this.method = value;
                    }

                }


                /**
                 * 
                 * 					The default method to invoke if no match.
                 * 				
                 * 
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;attribute name="method" use="required" type="{http://kasource.org}javaMethodName" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Default {

                    @XmlAttribute(required = true)
                    protected String method;

                    /**
                     * Gets the value of the method property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getMethod() {
                        return method;
                    }

                    /**
                     * Sets the value of the method property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setMethod(String value) {
                        this.method = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="class" use="required" type="{http://kasource.org}javaClass" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class QueueThread {

        @XmlAttribute(name = "class", required = true)
        protected String clazz;

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="maximumPoolSize" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="corePoolSize" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="keepAliveTime" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ThreadPoolExecutor {

        @XmlAttribute
        protected Byte maximumPoolSize;
        @XmlAttribute
        protected Byte corePoolSize;
        @XmlAttribute
        protected BigInteger keepAliveTime;

        /**
         * Gets the value of the maximumPoolSize property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getMaximumPoolSize() {
            return maximumPoolSize;
        }

        /**
         * Sets the value of the maximumPoolSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setMaximumPoolSize(Byte value) {
            this.maximumPoolSize = value;
        }

        /**
         * Gets the value of the corePoolSize property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getCorePoolSize() {
            return corePoolSize;
        }

        /**
         * Sets the value of the corePoolSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setCorePoolSize(Byte value) {
            this.corePoolSize = value;
        }

        /**
         * Gets the value of the keepAliveTime property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getKeepAliveTime() {
            return keepAliveTime;
        }

        /**
         * Sets the value of the keepAliveTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setKeepAliveTime(BigInteger value) {
            this.keepAliveTime = value;
        }

    }

}
