//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.12 at 04:54:21 PM CEST 
//
/**
 * Configuration classes, used to configure the ka-event environment.
 **/
@javax.xml.bind.annotation.XmlSchema(namespace = "http://kasource.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.kasource.kaevent.config;
